Program APOSENTADORIA ;
VAR 
NOMELJ : STRING  ;
TPLJ : INTEGER  ;
IDADELJ : INTEGER  ;
SXLJ : CHAR ;

Begin

	WRITELN ('DIGITE O NOME DA PESSOA') ;
	READ (NOMELJ) ;
	WRITELN ('DIGITE O TEMPO DE TRABALHO');
	READ (TPLJ);
	WRITELN ('DIGITE A IDADE DA PESSOA') ;
	READ (IDADELJ);
	WRITELN ('DIGITE O SEXO DA PESSOA (F/M)');
	READ (SXLJ) ;
	IF ((SXLJ='M') AND (IDADELJ>65)) OR ((SXLJ='F') AND (IDADELJ>60) OR (TPLJ>30))
	THEN WRITELN (NOMELJ,'PODE  APOSENTAR')ELSE WRITELN (NOMELJ,  '  TEM QUE TRABALHAR MAIS');
  
End.