Program FOLHA_DE_PAGAMENTO;

 VAR
 FUNCIONARIOLL: STRING;
 HORASLL : INTEGER;
 SHORALL : REAL ;
 FILHOSLL : INTEGER ;
 SBRUTOLL : REAL ;
 INSSLL : REAL ;
 IRRFLL : REAL ;
 FAMILIALL : REAL ;
 LIQUIDOLL : REAL ;
 RESPLL : CHAR;
 
  Begin
	WRITELN ('---------------------------------') ;
  WRITELN ('------------ EMPRESA BRASIL --------');
  WRITE ('NOMEDO FUNCIONÁRIO : ');
  READ (FUNCIONARIOLL);
  WRITE ('HORAS TRABALHADAS  : ');
  READ (HORASLL);
  WRITE ('SALARIO HORA :');
  READ (SHORALL);
  WRITE ('FILHOS:');
  READ (FILHOSLL);
  WRITELN;
  WRITELN;
  WRITELN ('-------------------------------------');
  WRITELN ('DIGITE ENTER PARA GERAR O RELATÓRIO');
  READLN;


	// CALCULOS  
		
	SBRUTOLL:=SHORALL * HORASLL ;    
		
//CALCULO DO INSS	

	IF(SBRUTOLL <=1174.86) THEN INSSLL:=SBRUTOLL*0.08;
	IF (SBRUTOLL >=1174.87) AND (SBRUTOLL<=1958.10) THEN INSSLL:= SBRUTOLL*0.09;
	IF (SBRUTOLL >= 1958.11 ) AND (SBRUTOLL <= 3916.20) THEN INSSLL:= SBRUTOLL*0.11;
	IF (SBRUTOLL > 3916.20) THEN INSSLL := 430.78;
	
	//CALCULO IRRF
	
	IF (SBRUTOLL<= 1313.69) THEN IRRFLL :=0;
	IF (SBRUTOLL >= 1313.70) AND (SBRUTOLL <= 2625.12) THEN IRRFLL := SBRUTOLL*0.15 - 197.05;
	IF (SBRUTOLL >= 2625.12) THEN IRRFLL:= SBRUTOLL*0.275 -525.19;
	
	//CACULO FAMILIA FILHOS
	
	IF (SBRUTOLL <= 608.80) THEN FAMILIALL := 31.22*FILHOSLL;
	IF (SBRUTOLL >= 608.81) AND (SBRUTOLL <= 915.05) THEN FAMILIALL := 22*FILHOSLL;
	IF (SBRUTOLL > 915.05) THEN FAMILIALL := 0;
	
	LIQUIDOLL:= SBRUTOLL - INSSLL - IRRFLL + FAMILIALL;
	                               
	//TELA 2 INICIO 
		
	CLRSCR;
	WRITELN('EMPRESA BRASIL - TELA DE SAIDA ');
	WRITELN('----------------------------------------');
	WRITELN('FUNCIONARIO.............:', FUNCIONARIOLL);
	WRITELN('SALARIO BRUTO...........:', SBRUTOLL:0:2);
	WRITELN('DESCONTO INSS...........:', INSSLL:0:2);
	WRITELN('IRRF....................:',IRRFLL:0:2);
	WRITELN('SALARIO FAMILIA.........:', FAMILIALL:0:2);
	WRITELN('SALARIO LIQUIDO.........:', LIQUIDOLL:0:2);
	WRITE('------------------------------------------');

 
 End.
