Program ATIVIDADE_3 ;
VAR 
PRODUTOLJ :STRING;
PRECO_UNIDLJ :REAL;
QUANT_VENDLJ :INTEGER;
TOTALLJ : REAL;
DESCONTOLJ :REAL;
TOTAL_LIQUILJ: REAL;
TOTAL_PARCIALLJ:REAL ;
TOTAL_COMPRALJ:REAL;
RESPLJ :CHAR  ;

 Begin
      //TELA DE ENTRADA
 REPEAT
 CLRSCR  ;
 WRITELN ('SISTEMAS DE COMPRA/VENDA -TELA DE ENTRADA');
 WRITELN ('------------------------------');
 WRITE ('PRODUTO:');
 READLN (PRODUTOLJ);
 WRITE ('PREÇO UNITÁRIO:');
 READLN (PRECO_UNIDLJ) ;
 WRITELN ('QUANTIDADE');
 READLN (QUANT_VENDLJ);
 WRITELN ('----------------------------------------');
 
 //CALCULOS
 TOTAL_PARCIALLJ:=QUANT_VENDLJ*PRECO_UNIDLJ ;
 TOTAL_COMPRALJ :=TOTAL_COMPRALJ+TOTAL_PARCIALLJ;
 WRITELN ('TOTAL PARCIAL --------------:',TOTAL_PARCIALLJ :0:2) ;
 WRITELN ('TOTAL DA COMPRA-------------:',TOTAL_COMPRALJ :0:2) ;
 WRITELN ('----------------------------------------');
 WRITELN ('OUTRO PRODUTO ? (S/N) ');
 READLN (RESPLJ) ;
 UNTIL (RESPLJ ='N');
 //2TELA
 CLRSCR ;
 WRITELN ('SISTEMA COMPRA/VENDA - TELA SAÍDA');
 WRITELN ('----------------------------------------');
 WRITELN ('TOTAL:',TOTAL_COMPRALJ :0:2);
 
 End.
