Program VETORES ;

 VAR NOMELL: ARRAY [1..10] OF STRING;
	NOTA1LL: ARRAY [1..10] OF REAL;
	NOTA2LL: ARRAY [1..10] OF REAL;
	FALTASLL: ARRAY [1..10] OF INTEGER;
	MEDIALL: ARRAY [1..10] OF REAL;
	SITLL:   ARRAY [1..10] OF STRING;
	X: INTEGER; //ORDEM DO VETOR
	
	APLL: INTEGER;
	RNLL: INTEGER;
	RFLL: INTEGER;
	MENORLL: REAL;
	MAIORLL: REAL;
	MGTLL: REAL;
	ACIMALL: INTEGER;
	ABAIXOLL: INTEGER; //VARIAVEIS SEGUNDA TELA
	
 Begin
  FOR X:=1 TO 10 DO BEGIN //INICIO DO LAÇO FOR
  CLRSCR;
  WRITELN ('SISTEMA EXEMPLO VETORES');
  WRITELN ('----------------------------------');
  WRITE   ('NOME: ');
  READLN  (NOMELL[X]);
  WRITE   ('NOTA 1: ');
  READLN  (NOTA1LL[X]);
  WRITE   ('NOTA 2: ');
  READLN  (NOTA2LL[X]);
  WRITE   ('FALTAS: ');
  READLN  (FALTASLL[X]);
  WRITELN ('----------------------------------');
  
  MEDIALL[X]:=(NOTA1LL[X]+NOTA2LL[X])/2;
  
  IF (MEDIALL[X]>=7) AND (FALTASLL[X]<=25) THEN SITLL[X]:='APROVADO';
  IF (MEDIALL[X]<7)  AND (FALTASLL[X]<=25) THEN SITLL[X]:='REPROVADO POR NOTA';
  IF (FALTASLL[X]>25)                      THEN SITLL[X]:='REPROVADO POR FREQUÊNCIA';
  
  WRITELN ('MÉDIA: ', MEDIALL[X]:0:2);
  WRITELN ('SITUAÇÃO: ', SITLL[X]);
  WRITELN ('----------------------------------');
  WRITELN;
  WRITELN ('TECLE ENTER PARA CONTINUAR');
  READLN;
  
  MGTLL:= MGTLL+MEDIALL[X]/10;
  
  END; //FECHA O LAÇO FOR
  
  FOR X:= 1 TO 10 DO BEGIN
  IF  SITLL[X]='APROVADO'             THEN APLL:=APLL+1;
  IF  SITLL[X]='APROVADO NOTA'        THEN RNLL:=RNLL+1;
  IF  SITLL[X]='REPROVADO FREQUENCIA' THEN RFLL:=RFLL+1;
  IF  MEDIALL[X]>MAIORLL              THEN MAIORLL:= MEDIALL[X];
  IF  MEDIALL[X]<MENORLL              THEN MENORLL:=MEDIALL[X];
  IF  MEDIALL[X]>MGTLL                THEN ACIMALL:=ACIMALL+1
                                      ELSE ABAIXOLL:=ABAIXOLL+1;    
  
  WRITELN ('SISTEMA EXEMPLO VETORES');
  WRITELN ('----------------------------------');
  WRITELN;
  WRITELN ('RESUMO FINAL');
  WRITELN;
  WRITELN ('APROVADOS %: ', APLL);
  WRITELN ('REPROVADOS POR NOTA %: ', RNLL);
  WRITELN ('REPROVADO POR FREQUENCIA %:', RFLL);
  WRITELN ('MAIOR NOTA: ', MAIORLL:0:2);
  WRITELN ('MENOR NOTA: ', MENORLL:0:2);
  WRITELN ('% ALUNOS ACIMA  DA MÉDIA:', ACIMALL);
  WRITELN ('% ALUNOS ABAIXO DA MÉDIA:', ABAIXOLL);
  WRITELN ('----------------------------------');
  WRITELN ('TECLE ENTER PARA FINALIZAR:');
  READLN;
  END;
      
 End.
