Program LUCIANO_LIMA;
 VAR
 
	FUNCIONARIOLL: STRING;
  HORASLL: REAL;
  SALARIOHORALL: REAL;
  FILHOSLL: REAL;
  SALARIOBRUTOLL: REAL;
  DESCONTOLL: REAL;
  IRRFLL: REAL;
  FAMILIALL: REAL;
  SALARIOLIQUIDOLL: REAL;
  
  
  
 Begin
  WRITELN('ATIVIDADE PROGRAMAÇÃO 2');
  WRITELN('---------------------------------------------');
  WRITE('FUNCIONARIO:');
  READLN(FUNCIONARIOLL);
  WRITE('HORAS TRABALHADAS:');
  READLN(HORASLL);
  WRITE('SALARIO HORA');
  READLN(SALARIOHORALL);
  WRITE('FILHOS MENORES DE 14 ANOS OU INVALIDOS');
  READLN(FILHOSLL);
  WRITELN('---------------------------------------------');
  WRITE('ENTER PARA GERAR RELATORIO');
  
  
  //INICIO DOS CALCULOS//
  
  SALARIOBRUTOLL=HORASLL*SALARIOHORALL
  SALARIOBRUTOLL
  

  IF(SALARIOBRUTOLL<=1174.86) THEN DESCONTOLL=SALARIBRUTOLL*0.08
                              ELSE IF(SALARIOBRUTOLL >1174.86) AND (SALARIOBRUTOLL<=1958.10)
                              THEN DESCONTOLL=SALARIOBRUTOLL*0.09
                              ELSE IF(SALARIOBRUTOLL> 1958.10) AND (SALARIOBRUTOLL<=3916.20)
						THEN DESCONTOLL=SALARIOBRUTOLL*0.11 
                              ELSE DESCONTOLL=SALARIOBRUTOLL-430.78
  IF(SALARIOBRUTOLL=>1313.70) AND (SALARIOBRUTOLL<2625.12)
  THEN IRRFLL=(SALABRUTOLL*0.15)-197.05
ELSE IF (SALARIOBRUTOLL>2625.12) 
THEN IRRFLL=(SALARIOBRUTOLL*0.275)-525.19
ELSE IRRFLL=WRITELN('ISENTO');

 IF (SALARIOBRUTOLL<681.80)
THEN FAMILIALL=FILHOSLL*31.22
ELSE IF(SALARIOBRUTOLL>608.80) AND (SALARIOBRUTOLL<915.06)
THEN FAMILIALL=FILHOSLL*22
ELSE FAMILIALL=0
SALARIOLIQUIDOLL=SALARIOBRUTOLL-DESCONTOLL-IRRFLL+FAMILIALL


//FIM DOS CALCULOS//
WRITELN('EMPRESA BRASIL');
WRITELN('----------------------------------------');
WRITELN('FUNCIONARIO:', FUNCIONARIOLL);
WRITELN('SALARIO BRUTO:', SALARIOBRUTOLL:0:2);
WRITELN('DESCONTO INSS:', DESCONTOLL:0:2);
WRITELN('IRRF:',IRRFLL:0:2);
WRITELN('SALARIO FAMILIA:', FAMILIALL:0:2);
WRITELN('SALARIO LIQUIDO:', SALARIOLIQUIDOLL:0:2);
WRITE('------------------------------------------------------');




						 
  
  
 End.
