Program Atividade2 ;
var
NOMEDOALUNO :STRING;
P1 : REAL ;
P2 : REAL ;
PPS : REAL  ;
ATIVIDADES : REAL  ;
FALTA : REAL  ;
MEDIAFINAL: REAL  ;
SIT : STRING;
 Begin
 clrscr;
 writeln ('SISTEMA DE MÉDIA ');
 WRITE ('NOME DO ALUNO') ;
 READLN (NOMEDOALUNO);
 WRITELN ('NOTA DA PROVA1');
 READLN (P1);
 WRITELN ('NOTA DA PROVA 2');
 READLN (P2);
 WRITELN ('ATIVIDADES');
 READ (ATIVIDADES);
 WRITELN ('NÚMERO DE FALTAS');
 READ (FALTA);
 WRITELN ('TECLE ENTER PARA GERAAR O BOLETIM');
 READLN;
  MEDIAFINAL := (P1*0.3)+(P2*0.3)+(PPS*0.2)+(ATIVIDADES*0.2);
  IF (FALTA<10) THEN SIT:=REPROVADO_FREQUENCIA 
  			ELSE  IF (MEDIA>=7) THEN SIT:= APROVADO
                                   ELSE SIT:= REROVADO_NOTA;
                                   
 
  
 End.
