   Program NOTAS ;

 VAR 
 	NOMELL: ARRAY [1..10] OF STRING;
	NOTA1LL: ARRAY [1..10] OF REAL;
	NOTA2LL: ARRAY [1..10] OF REAL;
	FALTASLL: ARRAY [1..10] OF INTEGER;
	MEDIALL: ARRAY [1..10] OF REAL;
	SITLL:   ARRAY [1..10] OF STRING;
	X: INTEGER; //PONTEIRO DO VETOR  	
	APRLL: INTEGER;//CONTADOR APROVADO
	RNLL: INTEGER; //CONTADOR REPROVADO
	RFLL: INTEGER; //CONTADOR REPROVADO FREQUENCIA

	
	BEGIN
	
	CLRSCR;
	WRITELN ('SISTEMAS ALUNOS ');
	WRITELN ('---------------------------');
	For x := 1 to 10 DO BEGIN //INICIO LAÇO FOR
	WRITELN ('ALUNO',X);
	WRITE ('--------NOME DO ALUNO-------:');
	READ (NOMELL[X]);
	WRITE ('------NOTA DA P1------------:');
	READ (NOTA1LL[X]);
	WRITE ('------NOTA DA P2------------:');
	READ (NOTA2LL[X]);
	WRITE ('------FALTAS----------------:');
	READ (FALTASLL[X]);
	WRITELN ('---------------------------');
	
	//INICIO DOS CALCULOS 
	
	MEDIALL [X]:=(NOTA1LL[X] + NOTA2LL[X])/2;
	
	IF (MEDIALL [X] >=7) AND  (FALTASLL[X] <=10 ) THEN BEGIN SITLL [X] := 'APROVADO';
	APRLL:=APRLL +1;
				END;
	IF (MEDIALL [X] <7) AND (FALTASLL [X] <=10 ) THEN BEGIN SITLL [X] := 'REPROVADO POR NOTA';
	RNLL:=RNLL +1;
				END;
	IF (FALTASLL [X] >10 )                       THEN BEGIN SITLL [X] := 'REPROVADO POR FREQUÊNCIA';
	RFLL:= RFLL +1;
				END;
	
	WRITELN ('MEDIA FINAL  :',MEDIALL [X]:0:2);
	WRITELN ('SITUAÇÃO :',SITLL [X]);
	WRITELN ('----------------------------');
	WRITELN ( '--RESUMO FINAL--');
	WRITELN ('APROVADOS',APRLL);
	WRITELN ('REPROVADO NOTAS',RNLL);
	WRITELN ('REPROVADO FREQUÊNCIA',RFLL);
	WRITELN ('----------------------------');
	WRITELN ('TECLE ENTER PARA TERMINAR');
	
	
	END
 End.
