Program SEGURO_DE_VIDA ;
VAR
NOMESEGURADOLS :STRING ;
IDADELS: INTEGER ;
SEXOLS :CHAR  ;
CASCOLS : REAL ;
BRUTOLS :REAL;
VALORVISTALS : REAL ;
VALOR3XLS: REAL ;
VALOR9X: REAL ;
FRANQLS: REAL ;
SNLS: CHAR ;


Begin
WRITELN ('SISTEMAS DE SEGUROS');
WRITELN ('-----------------------');
WRITELN ('NOME DO SEGURADO');
READ (NOMESEGURADOLS);
WRITELN ('IDADE-------------------');
READ (IDADELS);
WRITELN ('SEXO---------------------');
READ (SEXOLS);
WRITELN ('-------------------------');

IF (SEXOLS='M') AND (IDADELS>18) AND (IDADELS<30) THEN 
 BRUTOLS:=CASCOLS*0.087 ; FRANQLS:=BRUTOLS*0.10;
BEGIN 
IF (SEXOLS='F') AND (IDADELS>18) AND (IDADELS<30) THEN
BRUTOLS:=CASCOLS*0.067 ; FRAMQLS:=BRUTOLS*0.09 ;
BEGIN
IF (IDADELS>=30) AND (IDADELS<=60) THEN
BRUTOLS:=CASCO*0.047 ; FRANQLS:=BRUTO*0.07;
BEGIN
IF (IDADELS>=60) OR ((IDADELS>55) AND SEXLS='F') THEN
BRUTOLS:=CASCOLS*0.077; FRANQLS:=BRUTOLS*0.11;
BEGIN 

VALORVISTALS:=BRUTOLS*0.87;
VALOR3X:=BRUTOLS/3 ;
VALOR9X:=BRUTOLS*1.12/(9);

repeat
WRITELN ('SAIDA');
WRITELN ('-----------------------------');
WRITELN ('BRUTO------------------------',BRUTOLS:0:2);
WRITELN ('VALOR A VISTA ---------------',VALORVISTALS:0:2);
WRITELN ('VALOR EM 3 PARCELAS ---------',VALOR3XLS:0:2);
WRITELN ('VALOR EM 9 PARCELAS ---------',VALOR9X:0:2);
WRITELN ('FRANQUIA --------------------',FRANQLS:0:2);
WRITELN ('-----------------------------');
WRITELN ('REALIZAR UMA NOVA CONSULTA ? < S/N >');
READ (SNLS);
UNTIL (SNLS='N')
End.