Program VETORES ;

 VAR NOMEBT: ARRAY [1..10] OF STRING;
	NOTA1BT: ARRAY [1..10] OF REAL;
	NOTA2BT: ARRAY [1..10] OF REAL;
	FALTASBT: ARRAY [1..10] OF INTEGER;
	MEDIABT: ARRAY [1..10] OF REAL;
	SITBT:   ARRAY [1..10] OF STRING;
	X: INTEGER; //ORDEM DO VETOR
	
	APBT: INTEGER;
	RNBT: INTEGER;
	RFBT: INTEGER;
	MENORBT: REAL;
	MAIORBT: REAL;
	MGTBT: REAL;
	ACIMABT: INTEGER;
	ABAIXOBT: INTEGER; //VARIAVEIS SEGUNDA TELA
	
 Begin
  FOR X:=1 TO 10 DO BEGIN //INICIO DO LAÇO FOR
  CLRSCR;
  WRITELN ('SISTEMA EXEMPLO VETORES');
  WRITELN ('----------------------------------');
  WRITE   ('NOME: ');
  READLN  (NOMEBT[X]);
  WRITE   ('NOTA 1: ');
  READLN  (NOTA1BT[X]);
  WRITE   ('NOTA 2: ');
  READLN  (NOTA2BT[X]);
  WRITE   ('FALTAS: ');
  READLN  (FALTASBT[X]);
  WRITELN ('----------------------------------');
  
  MEDIABT[X]:=(NOTA1BT[X]+NOTA2BT[X])/2;
  
  IF (MEDIABT[X]>=7) AND (FALTASBT[X]<=25) THEN SITBT[X]:='APROVADO';
  IF (MEDIABT[X]<7)  AND (FALTASBT[X]<=25) THEN SITBT[X]:='REPROVADO POR NOTA';
  IF (FALTASBT[X]>25)                      THEN SITBT[X]:='REPROVADO POR FREQUÊNCIA';
  
  WRITELN ('MÉDIA: ', MEDIABT[X]:0:2);
  WRITELN ('SITUAÇÃO: ', SITBT[X]);
  WRITELN ('----------------------------------');
  WRITELN;
  WRITELN ('TECLE ENTER PARA CONTINUAR');
  READLN;
  
  MGTBT:= MGTBT+MEDIABT[X]/10;
  
  END; //FECHA O LAÇO FOR
  
  FOR X:= 1 TO 10 DO BEGIN
  IF  SITBT[X]='APROVADO'             THEN APBT:=APBT+1;
  IF  SITBT[X]='APROVADO NOTA'        THEN RNBT:=RNBT+1;
  IF  SITBT[X]='REPROVADO FREQUENCIA' THEN RFBT:=RFBT+1;
  IF  MEDIABT[X]>MAIORBT              THEN MAIORBT:= MEDIABT[X];
  IF  MEDIABT[X]<MENORBT              THEN MENORBT:=MEDIABT[X];
  IF  MEDIABT[X]>MGTBT                THEN ACIMABT:=ACIMABT+1
                                      ELSE ABAIXOBT:=ABAIXOBT+1;    
  
  WRITELN ('SISTEMA EXEMPLO VETORES');
  WRITELN ('----------------------------------');
  WRITELN;
  WRITELN ('RESUMO FINAL');
  WRITELN;
  WRITELN ('APROVADOS %: ', APBT);
  WRITELN ('REPROVADOS POR NOTA %: ', RNBT);
  WRITELN ('REPROVADO POR FREQUENCIA %:', RFBT);
  WRITELN ('MAIOR NOTA: ', MAIORBT:0:2);
  WRITELN ('MENOR NOTA: ', MENORBT:0:2);
  WRITELN ('% ALUNOS ACIMA  DA MÉDIA:', ACIMABT);
  WRITELN ('% ALUNOS ABAIXO DA MÉDIA:', ABAIXOBT);
  WRITELN ('----------------------------------');
  WRITELN ('TECLE ENTER PARA FINALIZAR:');
  READLN;
  END;
      
 End.
